### ISSUE TITLE
cannot export images that cross 180 longitude

### ISSUE THREAD

**Issue by seandepagnier** [makinacorpus/landez#51]
It would be nice to be able to export images that cross the date line, but currently there is no way to do this, as longitudes are bounded to -180 to 180, and the logic also doesn't deal with a larger minlon and smaller maxlon.

**Comment by leplatrem** [comment]
Good catch, don't hesitate to open a pull-request with a small test that reproduces the problem, and if you have a fix don't forget to update the changelog :)
