### ISSUE TITLE
Making Blank mbtiles

### ISSUE THREAD

**Issue by moccand** [makinacorpus/landez#61]
My process is to make 1 mbtiles file for each WMS i need (20) and then merge those files together. 
To do so i need to get at least one mbtiles (use as base) with my full project coverage (see #19 ).

But calling one WMS on a coverage that is not relevent make the process very slow (so many calls made just for a blank png). So i wonder if building a "blank" mbtiles would help me.

=> is it possible to create mbitiles over a predefined bbox, for n zoomlevels and only blank tiles ? In my process i would have 1 "blank" mbtiles that will be used to merge 20 "real" mbtiles.

**Comment by leplatrem** [comment]
Some ideas that come into my mind:
- create a Mapnik stylesheet that renders nothing and generate a MBTiles for the area that you need
- or create a blank tile PNG and write a little script that will create folders and symlinks to it. Then pack the whole folder tree as a MBTiles
- or put a white background in the map view that is going to show the MBTiles :)
